# Generated by Django 5.2.6 on 2026-04-15 11:59

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='\\\\NAS_ZdC\\home\\Github\\FoodScale\\media'), upload_to='', verbose_name='Imagen')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripcion breve')),
                ('long_description', models.CharField(max_length=1000, verbose_name='Descripcion detallada')),
            ],
            options={
                'verbose_name': 'Familia de alimentos',
                'verbose_name_plural': 'Familias de alimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('picture', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='\\\\NAS_ZdC\\home\\Github\\FoodScale\\media'), upload_to='', verbose_name='Imagen')),
                ('id', models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, default='', max_length=150, verbose_name='Descripcion')),
                ('nutrients', models.JSONField(blank=True, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='FoodAPP.ingredientfamily')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
