# Generated by Django 5.2.6 on 2026-04-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1, verbose_name='Cantidad en gramos')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isUsedIn', to='FoodAPP.ingredient', verbose_name='Ingrediente')),
            ],
            options={
                'verbose_name': 'Combinacion de ingredientes',
                'verbose_name_plural': 'Combinaciones de ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Desayuno'), (1, 'Almuerzo'), (2, 'Comida'), (3, 'Merienda'), (4, 'Cena'), (4, 'Despues de cena')], help_text='Determina el tipo de comida en el dia', verbose_name='Tipo de comida')),
                ('dateTime', models.DateTimeField(auto_now_add=True, verbose_name='Date and time')),
                ('components', models.ManyToManyField(blank=True, through='FoodAPP.CombinationPosition', to='FoodAPP.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='combinationposition',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultant_product', to='FoodAPP.meal'),
        ),
    ]
