# Generated by Django 5.2.6 on 2026-04-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAPP', '0003_meal_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
    ]
