# Generated by Django 5.2.6 on 2026-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAPP', '0004_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='dateTime',
            field=models.DateTimeField(verbose_name='Date and time'),
        ),
    ]
