# Generated by Django 5.2.6 on 2026-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAPP', '0005_alter_meal_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Desayuno'), (1, 'Almuerzo'), (2, 'Comida'), (3, 'Merienda'), (4, 'Cena'), (5, 'Despues de cena')], help_text='Determina el tipo de comida en el dia', verbose_name='Tipo de comida'),
        ),
    ]
