# Generated by Django 5.2.6 on 2026-04-14 15:21

import UsersAPP.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAPP', '0002_remove_user_type_user_is_vip_user_user_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', UsersAPP.managers.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='validated',
        ),
    ]
