# Generated by Django 5.2.6 on 2026-04-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAPP', '0004_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
