# Generated by Django 5.2.6 on 2025-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INSTALLATION_NAME', models.CharField(default='My installation', help_text='The name of the installation', max_length=100, verbose_name='Name of the installation')),
                ('INSTALLATION_ADDR1', models.CharField(default='My street and number', help_text='The address of the installation', max_length=200, verbose_name='Address of the installation')),
                ('INSTALLATION_ADDR2', models.CharField(blank=True, help_text='The address of the installation', max_length=200, null=True, verbose_name='Address of the installation (Line 2)')),
                ('INSTALLATION_PHONE', models.CharField(blank=True, help_text='The phone number of the installation', max_length=200, null=True, verbose_name='Phone of the installation')),
                ('INSTALLATION_EMAIL', models.EmailField(blank=True, help_text='The contact email of the installation', max_length=254, null=True, verbose_name='Contact email of the installation')),
                ('PUBLISH_TO_WEB', models.BooleanField(default=False, help_text="Enables publishing any product creation/update to the installation's web to keep it updated", verbose_name='Publish products update to the web')),
                ('VERSION_AUTO_UPDATE', models.BooleanField(default=False, help_text='Allows to automatically update the software from official repository (requires internet access)', verbose_name='Automatic updates')),
                ('VERSION_CODE', models.CharField(blank=True, default='', max_length=10, verbose_name='Code of the current version')),
                ('LAN_IP', models.GenericIPAddressField(blank=True, null=True)),
                ('SEC2LOGOUT', models.PositiveSmallIntegerField(default=0, help_text='Seconds after when, the user would need to login again', verbose_name='Seconds to logout')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
