# Generated by Django 5.2.6 on 2026-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_webcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontact',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
    ]
