# Generated by Django 5.2.6 on 2026-04-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_webcontact_is_responded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
